# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.7/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/edwardgallyot/JUCE_CMake_Projects/Ed_Midi_Test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/edwardgallyot/JUCE_CMake_Projects/Ed_Midi_Test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.19.7/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.19.7/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.19.7/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.19.7/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.19.7/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.19.7/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/edwardgallyot/JUCE_CMake_Projects/Ed_Midi_Test/CMakeFiles /Users/edwardgallyot/JUCE_CMake_Projects/Ed_Midi_Test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/edwardgallyot/JUCE_CMake_Projects/Ed_Midi_Test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/edwardgallyot/JUCE_CMake_Projects/Ed_Midi_Test/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ed_Midi_Test_AU

# Build rule for target.
Ed_Midi_Test_AU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ed_Midi_Test_AU
.PHONY : Ed_Midi_Test_AU

# fast build rule for target.
Ed_Midi_Test_AU/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/build
.PHONY : Ed_Midi_Test_AU/fast

#=============================================================================
# Target rules for targets named Ed_Midi_Test_Standalone

# Build rule for target.
Ed_Midi_Test_Standalone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ed_Midi_Test_Standalone
.PHONY : Ed_Midi_Test_Standalone

# fast build rule for target.
Ed_Midi_Test_Standalone/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/build
.PHONY : Ed_Midi_Test_Standalone/fast

#=============================================================================
# Target rules for targets named Ed_Midi_Test_VST3

# Build rule for target.
Ed_Midi_Test_VST3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ed_Midi_Test_VST3
.PHONY : Ed_Midi_Test_VST3

# fast build rule for target.
Ed_Midi_Test_VST3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/build
.PHONY : Ed_Midi_Test_VST3/fast

#=============================================================================
# Target rules for targets named Ed_Midi_Test_All

# Build rule for target.
Ed_Midi_Test_All: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ed_Midi_Test_All
.PHONY : Ed_Midi_Test_All

# fast build rule for target.
Ed_Midi_Test_All/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_All.dir/build.make CMakeFiles/Ed_Midi_Test_All.dir/build
.PHONY : Ed_Midi_Test_All/fast

#=============================================================================
# Target rules for targets named Ed_Midi_Test

# Build rule for target.
Ed_Midi_Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ed_Midi_Test
.PHONY : Ed_Midi_Test

# fast build rule for target.
Ed_Midi_Test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/build
.PHONY : Ed_Midi_Test/fast

MidiProcessor.o: MidiProcessor.cpp.o

.PHONY : MidiProcessor.o

# target to build an object file
MidiProcessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/MidiProcessor.cpp.o
.PHONY : MidiProcessor.cpp.o

MidiProcessor.i: MidiProcessor.cpp.i

.PHONY : MidiProcessor.i

# target to preprocess a source file
MidiProcessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/MidiProcessor.cpp.i
.PHONY : MidiProcessor.cpp.i

MidiProcessor.s: MidiProcessor.cpp.s

.PHONY : MidiProcessor.s

# target to generate assembly for a file
MidiProcessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/MidiProcessor.cpp.s
.PHONY : MidiProcessor.cpp.s

PluginEditor.o: PluginEditor.cpp.o

.PHONY : PluginEditor.o

# target to build an object file
PluginEditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/PluginEditor.cpp.o
.PHONY : PluginEditor.cpp.o

PluginEditor.i: PluginEditor.cpp.i

.PHONY : PluginEditor.i

# target to preprocess a source file
PluginEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/PluginEditor.cpp.i
.PHONY : PluginEditor.cpp.i

PluginEditor.s: PluginEditor.cpp.s

.PHONY : PluginEditor.s

# target to generate assembly for a file
PluginEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/PluginEditor.cpp.s
.PHONY : PluginEditor.cpp.s

PluginProcessor.o: PluginProcessor.cpp.o

.PHONY : PluginProcessor.o

# target to build an object file
PluginProcessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/PluginProcessor.cpp.o
.PHONY : PluginProcessor.cpp.o

PluginProcessor.i: PluginProcessor.cpp.i

.PHONY : PluginProcessor.i

# target to preprocess a source file
PluginProcessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/PluginProcessor.cpp.i
.PHONY : PluginProcessor.cpp.i

PluginProcessor.s: PluginProcessor.cpp.s

.PHONY : PluginProcessor.s

# target to generate assembly for a file
PluginProcessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/PluginProcessor.cpp.s
.PHONY : PluginProcessor.cpp.s

Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.o: Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o

Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.i: Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i

Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.s: Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s

Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.o: Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o

Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.i: Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i

Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.s: Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s

Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.o: Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o

Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.i: Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i

Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.s: Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.cpp.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.cpp.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.cpp.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.cpp.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.mm.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_AU.dir/build.make CMakeFiles/Ed_Midi_Test_AU.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_Standalone.dir/build.make CMakeFiles/Ed_Midi_Test_Standalone.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test_VST3.dir/build.make CMakeFiles/Ed_Midi_Test_VST3.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.mm.s

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.o: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.cpp.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.cpp.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.cpp.o

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.i: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.cpp.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.cpp.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.cpp.i

Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.s: Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.cpp.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.cpp.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.cpp.s

Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.o: Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o

Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.i: Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i

Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.s: Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s

Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.o: Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o

Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.i: Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i

Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.s: Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s

Users/edwardgallyot/JUCE/modules/juce_core/juce_core.o: Users/edwardgallyot/JUCE/modules/juce_core/juce_core.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_core/juce_core.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_core/juce_core.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_core/juce_core.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_core/juce_core.mm.o

Users/edwardgallyot/JUCE/modules/juce_core/juce_core.i: Users/edwardgallyot/JUCE/modules/juce_core/juce_core.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_core/juce_core.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_core/juce_core.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_core/juce_core.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_core/juce_core.mm.i

Users/edwardgallyot/JUCE/modules/juce_core/juce_core.s: Users/edwardgallyot/JUCE/modules/juce_core/juce_core.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_core/juce_core.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_core/juce_core.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_core/juce_core.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_core/juce_core.mm.s

Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.o: Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.mm.o

Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.i: Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.mm.i

Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.s: Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.mm.s

Users/edwardgallyot/JUCE/modules/juce_events/juce_events.o: Users/edwardgallyot/JUCE/modules/juce_events/juce_events.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_events/juce_events.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_events/juce_events.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_events/juce_events.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_events/juce_events.mm.o

Users/edwardgallyot/JUCE/modules/juce_events/juce_events.i: Users/edwardgallyot/JUCE/modules/juce_events/juce_events.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_events/juce_events.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_events/juce_events.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_events/juce_events.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_events/juce_events.mm.i

Users/edwardgallyot/JUCE/modules/juce_events/juce_events.s: Users/edwardgallyot/JUCE/modules/juce_events/juce_events.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_events/juce_events.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_events/juce_events.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_events/juce_events.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_events/juce_events.mm.s

Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.o: Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.mm.o

Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.i: Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.mm.i

Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.s: Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.mm.s

Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.o: Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o

Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.i: Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i

Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.s: Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s

Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.o: Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o

.PHONY : Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.o

# target to build an object file
Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o
.PHONY : Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o

Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.i: Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i

.PHONY : Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.i

# target to preprocess a source file
Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i
.PHONY : Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i

Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.s: Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s

.PHONY : Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.s

# target to generate assembly for a file
Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ed_Midi_Test.dir/build.make CMakeFiles/Ed_Midi_Test.dir/Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s
.PHONY : Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Ed_Midi_Test_All"
	@echo "... Ed_Midi_Test"
	@echo "... Ed_Midi_Test_AU"
	@echo "... Ed_Midi_Test_Standalone"
	@echo "... Ed_Midi_Test_VST3"
	@echo "... MidiProcessor.o"
	@echo "... MidiProcessor.i"
	@echo "... MidiProcessor.s"
	@echo "... PluginEditor.o"
	@echo "... PluginEditor.i"
	@echo "... PluginEditor.s"
	@echo "... PluginProcessor.o"
	@echo "... PluginProcessor.i"
	@echo "... PluginProcessor.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_basics/juce_audio_basics.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_devices/juce_audio_devices.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_formats/juce_audio_formats.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_1.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_2.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_3.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_4.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_RTAS_utils.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST_utils.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_processors/juce_audio_processors.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_audio_utils/juce_audio_utils.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_core/juce_core.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_core/juce_core.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_core/juce_core.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_data_structures/juce_data_structures.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_events/juce_events.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_events/juce_events.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_events/juce_events.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_graphics/juce_graphics.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_gui_basics/juce_gui_basics.s"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.o"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.i"
	@echo "... Users/edwardgallyot/JUCE/modules/juce_gui_extra/juce_gui_extra.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/edwardgallyot/JUCE_CMake_Projects/Ed_Midi_Test/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

